export const sample_foods = [
  {
    name: "Chuckle-Chicken Chimichanga",
    cookTime: "10-20",
    price: 5,
    imageUrl: "image-1.jpg",
    tags: ["Kids", "Breakfast", "FastFood"],
  },
  {
    name: "Shrimp and Rice Burrito",
    cookTime: "10-20",
    price: 5,
    imageUrl: "image-1.jpg",
    tags: ["Kids", "Breakfast", "FastFood"],
  },
  {
    name: "Vegetarian Black Bean Burrito",
    cookTime: "10-20",
    price: 5,
    imageUrl: "image-1.jpg",
    tags: ["Kids", "Breakfast", "Fry"],
  },
  {
    name: "Bean and Cheese Burrito",
    cookTime: "10-20",
    price: 5,
    imageUrl: "image-1.jpg",
    tags: ["Kids", "Breakfast", "FastFood"],
  },
  {
    name: "Gluten-free Burrito",
    cookTime: "10-20",
    price: 5,
    imageUrl: "image-1.jpg",
    tags: ["Kids", "Breakfast", "Lunch"],
  },
  {
    name: "Sizzling Steak Burrito",
    cookTime: "15-25",
    price: 8,
    imageUrl: "image-1.jpg",
    tags: ["Lunch", "FastFood"],
  },
  {
    name: "Classic Margherita Pizza",
    cookTime: "12-22",
    price: 7,
    imageUrl: "image-1.jpg",
    tags: ["Dinner", "Pizza"],
  },
  {
    name: "Spicy Chicken Burger",
    cookTime: "15-20",
    price: 6,
    imageUrl: "image-1.jpg",
    tags: ["Lunch", "Hamburger"],
  },
  {
    name: "BBQ Bacon Burger",
    cookTime: "15-20",
    price: 7,
    imageUrl: "image-1.jpg",
    tags: ["Lunch", "Burger", "FastFood"],
  },
  {
    name: "Mushroom Supreme Pizza",
    cookTime: "12-22",
    price: 8,
    imageUrl: "image-1.jpg",
    tags: ["Dinner", "Pizza"],
  },
  {
    name: "Veggie Delight Wrap",
    cookTime: "10-15",
    price: 6,
    imageUrl: "image-1.jpg",
    tags: ["Lunch", "Vegetarian", "FastFood"],
  },
];


export const sample_tags = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Soup", count: 1 },
  { name: "Dinner", count: 2 },
  { name: "Burger", count: 2 },
  { name: "Mexican", count: 4 },
  { name: "Dessert", count: 1 },
  { name: "Vegetarian", count: 2 },
  { name: "Dessert", count: 2 },
  { name: "Wraps", count: 2 },
  { name: "BBQ", count: 3 },
  { name: "Gourmet", count: 1 },
  { name: "Vegetarian", count: 3 },
];

export const sample_users = [
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: false,
  },
  {
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: true,
  },
  {
    name: "James Doe",
    email: "james@gmail.com",
    password: "12345",
    address: "Tokyo",
    isAdmin: true,
  },
  {
    name: "Loan Doe",
    email: "loan@gmail.com",
    password: "12345",
    address: "Los Angeles",
    isAdmin: true,
  },
  {
    name: "Emily Smith",
    email: "emily@gmail.com",
    password: "12345",
    address: "New York",
    isAdmin: false,
  },
  {
    name: "Michael Johnson",
    email: "michael@gmail.com",
    password: "12345",
    address: "London",
    isAdmin: true,
  },
  {
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    password: "12345",
    address: "Sydney",
    isAdmin: false,
  },
  {
    name: "Alex Johnson",
    email: "alex@gmail.com",
    password: "12345",
    address: "Chicago",
    isAdmin: false,
  },
  {
    name: "Olivia Williams",
    email: "olivia@gmail.com",
    password: "12345",
    address: "Paris",
    isAdmin: false,
  },
  {
    name: "Ethan Brown",
    email: "ethan@gmail.com",
    password: "12345",
    address: "Berlin",
    isAdmin: true,
  },
];
