export const sample_foods = [
  {
    id: "1",
    name: "Chuckle-Chicken Chimichanga",
    cookTime: "10-20",
    price: 5,
    favorite: false,
    stars: 1,
    imageUrl: "image-1.jpg",
    tags: ["Kids", "Breakfast", "FastFood"],
  },
  {
    id: "2",
    name: "Shrimp and Rice Burrito",
    cookTime: "10-20",
    price: 5,
    favorite: false,
    stars: 2,
    imageUrl: "image-1.jpg",
    tags: ["Kids", "Breakfast", "FastFood"],
  },
  {
    id: "3",
    name: "Vegetarian Black Bean Burrito",
    cookTime: "10-20",
    price: 5,
    favorite: false,
    stars: 5,
    imageUrl: "image-1.jpg",
    tags: ["Kids", "Breakfast", "Fry"],
  },
  {
    id: "4",
    name: "Bean and Cheese Burrito",
    cookTime: "10-20",
    price: 5,
    favorite: false,
    stars: 4.5,
    imageUrl: "image-1.jpg",
    tags: ["Kids", "Breakfast", "FastFood"],
  },
  {
    id: "5",
    name: "Gluten-free Burrito",
    cookTime: "10-20",
    price: 5,
    favorite: false,
    stars: 4.5,
    imageUrl: "image-1.jpg",
    tags: ["Kids", "Breakfast", "Lunch"],
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Soup", count: 1 },
];
